services:
  db_server:
    build:
      context: ./servers
      dockerfile: ./db_server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_IP: "0.0.0.0"
      DB_PORT: 8080

  async_asyncio:
    build:
      context: ./servers
      dockerfile: ./asyncio_server/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db_server
    environment:
      DB_IP: db_server
      DB_PORT: 8080
      SERVER_IP: "0.0.0.0"
      SERVER_PORT: 8080
    develop:
      watch:
        - action: rebuild
          path: ./asyncio_server
          target: .
        - action: rebuild
          path: ./commons
          target: /app/commons
